echo LICENSE > C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo Microsoft Dreamspark >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo MICROSOFT DREAMSPARK DIRECT >> C:\License.txt
echo SUBSCRIPTION AGREEMENT >> C:\License.txt
echo Last updated: June 2013 >> C:\License.txt
echo This is a subscription agreement (“agreement”) between Microsoft Corporation (or based on where you live, one of its affiliates) and you for the Microsoft DreamSpark Direct student offering (“DreamSpark Direct Subscription”). Please read it. For purposes of this agreement, the term “software” applies to the software provided to you under the DreamSpark Direct Subscription, which includes the media on which you received it, if any. >> C:\License.txt
echo 1.    DEFINITION OF YOU OR YOUR. "You", “your” or “student” means a person currently enrolled in and attending courses that lead to academic credit or certification through an accredited educational institution. >> C:\License.txt
echo 2.    TERMS FOR DREAMSPARK DIRECT SUBSCRIPTION. >> C:\License.txt
echo a.    DreamSpark Direct Subscription. Subject to the terms of this agreement, the DreamSpark Direct Subscription provides a subscription to access software. Microsoft may change the software or other offerings that it makes available under the DreamSpark Direct Subscription at any time without prior notice to you. >> C:\License.txt
echo b.    End of Student Status. The DreamSpark Direct Subscription is a special offering for students. Once you no longer qualify for the DreamSpark Direct Subscription (due to graduation or otherwise no longer meeting the definition of "you" above), your DreamSpark Direct Subscription will terminate; however, you may continue to use the software you obtained prior to termination of your student status subject to the terms of this agreement. >> C:\License.txt
echo c.   Termination. Microsoft may terminate the entire DreamSpark program or your specific DreamSpark Direct Subscription at any time without prior notice to you for any reason or no reason. >> C:\License.txt
echo 3.    DREAMSPARK DIRECT SUBSCRIPTION RIGHTS. >> C:\License.txt
echo a.  DreamSpark Direct Subscription Software. Your use of the software is subject to the license terms provided with the software, such as click-through license terms, except for any changes to those terms that are provided in this agreement. >> C:\License.txt
echo b.  Installation and Use Rights. You may install and use two (2) copies of the DreamSpark Direct Subscription software on your devices (a) to support your education; (b) in non-commercial research; or (c) to design, develop, test, and demonstrate software programs for the above purposes. The DreamSpark Direct Subscription and software are personal to you and may not be shared, transferred, resold, assigned or used to develop or maintain your own administrative or IT systems. >> C:\License.txt
echo c.  Using Windows Desktop Operating Systems.  Your DreamSpark Direct Subscription includes certain Windows operating system products. You may install these products only on a computer that is already licensed to run a full version of a Windows operating system on it, as evidenced by a valid Certificate of Authenticity (COA) for a Windows operating system affixed to the computer. >> C:\License.txt
echo d.   No commercial use. Except as provided below, you may not use the DreamSpark Direct Subscription software for commercial purposes or commercial software application development, publication or distribution unless you first purchase the appropriate commercial license(s) for the software. >> C:\License.txt
echo Windows Phone Application Requirements. To commercially publish and distribute a phone-based software application that you developed using the DreamSpark Subscription software, the application must be submitted through the Windows Phone Dev Center (https://dev.windowsphone.com/) for publication in the Windows Phone Store and comply with all applicable Windows Phone Store Application Provider requirements. >> C:\License.txt
echo Windows Application Requirements. To commercially publish and distribute a computer-based software application that you developed using the DreamSpark Subscription software, the application must be published in the Windows Store and comply with all applicable Windows Store Application Developer requirements. >> C:\License.txt
echo Xbox LIVE Indie Games Development Requirements. To commercially publish and distribute a console-based game or software application that you developed using the DreamSpark Subscription software, the application must be published to Xbox LIVE Indie Games and comply with all applicable Xbox LIVE Indie Games development requirements. >> C:\License.txt
echo              Visit the DreamSpark App Developer portal at https://www.dreamspark.com/Student/App-Development.aspx. >> C:\License.txt
echo 4.    PARENTAL OR LEGAL GUARDIAN CONSENT.  If you are under eighteen (18) years of age, your parent or legal guardian must provide verifiable consent before you may create a DreamSpark.com account or access any software through the DreamSpark Direct Subscription. If your parent or legal guardian does not provide their consent to the Microsoft DreamSpark student support team, you may not accept the terms of this agreement and the DreamSpark Direct Subscription will not be made available to you until such consent is given. >> C:\License.txt
echo 5.    NOT FOR RESALE SOFTWARE. You may not resell the software provided as part of the DreamSpark Direct Subscription. >> C:\License.txt
echo 6.    SUPPORT SERVICES. Software and other services provided under the DreamSpark Direct Subscription are provided “as is,” we do not provide support services for them. >> C:\License.txt
echo 7.    ENTIRE AGREEMENT. This agreement, and the terms for software, supplements, updates, Internet-based services and support services that you use, are the entire agreement for the software and support services. >> C:\License.txt
echo 8.    APPLICABLE LAW. >> C:\License.txt
echo a.  United States. If you acquired the DreamSpark Direct Subscription in the United States, Washington state law governs the interpretation of this agreement and applies to claims for breach of it, regardless of conflict of laws principles. The laws of the state where you live govern all other claims, including claims under state consumer protection laws, unfair competition laws, and in tort. >> C:\License.txt
echo b.  Outside the United States. If you live in any other country, the laws of that country apply. >> C:\License.txt
echo 9.    LEGAL EFFECT. This agreement describes certain legal rights. You may have other rights under the laws of your country. This agreement does not change your rights under the laws of your country if the laws of your country do not permit it to do so. >> C:\License.txt
echo 10.   DISCLAIMER OF WARRANTY. The DreamSpark Direct Subscription is provided “as-is.” You bear the risk of using/participating in it. Microsoft gives no express warranties, guarantees or conditions. You may have additional consumer rights under your local laws which this agreement cannot change. To the extent permitted under your local laws, Microsoft excludes the implied warranties of merchantability, fitness for a particular purpose and non-infringement. >> C:\License.txt
echo 11.   LIMITATION ON AND EXCLUSION OF REMEDIES AND DAMAGES. You can recover from Microsoft and its suppliers only direct damages up to U.S. $5.00. You cannot recover any other damages, including consequential, lost profits, special, indirect or incidental damages. >> C:\License.txt
echo For questions about DreamSpark and/or the DreamSpark Direct Subscription, please see https://www.dreamspark.com/Student/Support.aspx >> C:\License.txt
echo --------------------------------------------------------------------------------- >> C:\License.txt
echo Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX >> C:\License.txt
echo --------------------------------------------------------------------------------- >> C:\License.txt
echo ORACLE AMERICA, INC. ("ORACLE"), FOR AND ON BEHALF OF ITSELF AND ITS SUBSIDIARIES AND AFFILIATES UNDER COMMON CONTROL, IS WILLING TO LICENSE THE SOFTWARE TO YOU ONLY UPON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS CONTAINED IN THIS BINARY CODE LICENSE AGREEMENT AND SUPPLEMENTAL LICENSE TERMS (COLLECTIVELY "AGREEMENT"). PLEASE READ THE AGREEMENT CAREFULLY. BY SELECTING THE "ACCEPT LICENSE AGREEMENT" (OR THE EQUIVALENT) BUTTON AND/OR BY USING THE SOFTWARE YOU ACKNOWLEDGE THAT YOU HAVE READ THE TERMS AND AGREE TO THEM. IF YOU ARE AGREEING TO THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO BIND THE LEGAL ENTITY TO THESE TERMS. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT WISH TO BE BOUND BY THE TERMS, THEN SELECT THE "DECLINE LICENSE AGREEMENT" (OR THE EQUIVALENT) BUTTON AND YOU MUST NOT USE THE SOFTWARE ON THIS SITE OR ANY OTHER MEDIA ON WHICH THE SOFTWARE IS CONTAINED. >> C:\License.txt
echo 1. DEFINITIONS. "Software" means the software identified above in binary form that you selected for download, install or use (in the version You selected for download, install or use) from Oracle or its authorized licensees, any other machine readable materials (including, but not limited to, libraries, source files, header files, and data files), any updates or error corrections provided by Oracle, and any user manuals, programming guides and other documentation provided to you by Oracle under this Agreement. "General Purpose Desktop Computers and Servers" means computers, including desktop and laptop computers, or servers, used for general computing functions under end user control (such as but not specifically limited to email, general purpose Internet browsing, and office suite productivity tools). The use of Software in systems and solutions that provide dedicated functionality (other than as mentioned above) or designed for use in embedded or function-specific software applications, for example but not limited to: Software embedded in or bundled with industrial control systems, wireless mobile telephones, wireless handheld devices, kiosks, TV/STB, Blu-ray Disc devices, telematics and network control switching equipment, printers and storage management systems, and other related systems are excluded from this definition and not licensed under this Agreement. "Programs" means (a) Java technology applets and applications intended to run on the Java Platform, Standard Edition platform on Java-enabled General Purpose Desktop Computers and Servers; and (b) JavaFX technology applications intended to run on the JavaFX Runtime on JavaFX-enabled General Purpose Desktop Computers and Servers. “Commercial Features” means those features identified in Table 1-1 (Commercial Features In Java SE Product Editions) of the Java SE documentation accessible at http://www.oracle.com/technetwork/java/javase/documentation/index.html. “README File” means the README file for the Software accessible at http://www.oracle.com/technetwork/java/javase/documentation/index.html. >> C:\License.txt
echo 2. LICENSE TO USE. Subject to the terms and conditions of this Agreement including, but not limited to, the Java Technology Restrictions of the Supplemental License Terms, Oracle grants you a non-exclusive, non-transferable, limited license without license fees to reproduce and use internally the Software complete and unmodified for the sole purpose of running Programs. THE LICENSE SET FORTH IN THIS SECTION 2 DOES NOT EXTEND TO THE COMMERCIAL FEATURES. YOUR RIGHTS AND OBLIGATIONS RELATED TO THE COMMERCIAL FEATURES ARE AS SET FORTH IN THE SUPPLEMENTAL TERMS ALONG WITH ADDITIONAL LICENSES FOR DEVELOPERS AND PUBLISHERS. >> C:\License.txt
echo 3. RESTRICTIONS. Software is copyrighted. Title to Software and all associated intellectual property rights is retained by Oracle and/or its licensors. Unless enforcement is prohibited by applicable law, you may not modify, decompile, or reverse engineer Software. You acknowledge that the Software is developed for general use in a variety of information management applications; it is not developed or intended for use in any inherently dangerous applications, including applications that may create a risk of personal injury. If you use the Software in dangerous applications, then you shall be responsible to take all appropriate fail-safe, backup, redundancy, and other measures to ensure its safe use. Oracle disclaims any express or implied warranty of fitness for such uses. No right, title or interest in or to any trademark, service mark, logo or trade name of Oracle or its licensors is granted under this Agreement. Additional restrictions for developers and/or publishers licenses are set forth in the Supplemental License Terms. >> C:\License.txt
echo 4. DISCLAIMER OF WARRANTY. THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. ORACLE FURTHER DISCLAIMS ALL WARRANTIES, EXPRESS AND IMPLIED, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT. >> C:\License.txt
echo 5. LIMITATION OF LIABILITY. IN NO EVENT SHALL ORACLE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, DATA OR DATA USE, INCURRED BY YOU OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT, EVEN IF ORACLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ORACLE'S ENTIRE LIABILITY FOR DAMAGES HEREUNDER SHALL IN NO EVENT EXCEED ONE THOUSAND DOLLARS (U.S. $1,000). >> C:\License.txt
echo 6. TERMINATION. This Agreement is effective until terminated. You may terminate this Agreement at any time by destroying all copies of Software. This Agreement will terminate immediately without notice from Oracle if you fail to comply with any provision of this Agreement. Either party may terminate this Agreement immediately should any Software become, or in either party's opinion be likely to become, the subject of a claim of infringement of any intellectual property right. Upon termination, you must destroy all copies of Software. >> C:\License.txt
echo 7. EXPORT REGULATIONS. You agree that U.S. export control laws and other applicable export and import laws govern your use of the Software, including technical data; additional information can be found on Oracle's Global Trade Compliance web site (http://www.oracle.com/us/products/export). You agree that neither the Software nor any direct product thereof will be exported, directly, or indirectly, in violation of these laws, or will be used for any purpose prohibited by these laws including, without limitation, nuclear, chemical, or biological weapons proliferation. >> C:\License.txt
echo 8. TRADEMARKS AND LOGOS. You acknowledge and agree as between you >> C:\License.txt
echo and Oracle that Oracle owns the ORACLE and JAVA trademarks and all ORACLE- and JAVA-related trademarks, service marks, logos and other brand >> C:\License.txt
echo designations ("Oracle Marks"), and you agree to comply with the Third >> C:\License.txt
echo Party Usage Guidelines for Oracle Trademarks currently located at >> C:\License.txt
echo http://www.oracle.com/us/legal/third-party-trademarks/index.html . Any use you make of the Oracle Marks inures to Oracle's benefit. >> C:\License.txt
echo 9. U.S. GOVERNMENT LICENSE RIGHTS. If Software is being acquired by or on behalf of the U.S. Government or by a U.S. Government prime contractor or subcontractor (at any tier), then the Government's rights in Software and accompanying documentation shall be only those set forth in this Agreement. >> C:\License.txt
echo 10. GOVERNING LAW. This agreement is governed by the substantive and procedural laws of California. You and Oracle agree to submit to the exclusive jurisdiction of, and venue in, the courts of San Francisco, or Santa Clara counties in California in any dispute arising out of or relating to this agreement. >> C:\License.txt
echo 11. SEVERABILITY. If any provision of this Agreement is held to be unenforceable, this Agreement will remain in effect with the provision omitted, unless omission would frustrate the intent of the parties, in which case this Agreement will immediately terminate. >> C:\License.txt
echo 12. INTEGRATION. This Agreement is the entire agreement between you and Oracle relating to its subject matter. It supersedes all prior or contemporaneous oral or written communications, proposals, representations and warranties and prevails over any conflicting or additional terms of any quote, order, acknowledgment, or other communication between the parties relating to its subject matter during the term of this Agreement. No modification of this Agreement will be binding, unless in writing and signed by an authorized representative of each party. >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo Windows 7 Professional >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo MICROSOFT SOFTWARE LICENSE TERMS >> C:\License.txt
echo WINDOWS 7 PROFESSIONAL SERVICE PACK 1 >> C:\License.txt
echo These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. Printed-paper license terms, which may come with the software, may replace or modify any on-screen license terms. The terms also apply to any Microsoft >> C:\License.txt
echo ·	updates, >> C:\License.txt
echo ·	supplements, >> C:\License.txt
echo ·	Internet-based services, and >> C:\License.txt
echo ·	support services >> C:\License.txt
echo for this software, unless other terms accompany those items. If so, those terms apply. >> C:\License.txt
echo By using the software, you accept these terms. If you do not accept them, do not use the software. Instead, return it to the retailer for a refund or credit. If you cannot obtain a refund there, contact Microsoft or the Microsoft affiliate serving your country for information about Microsoft’s refund policies. See www.microsoft.com/worldwide. In the United States and Canada, call (800) MICROSOFT or see www.microsoft.com/info/nareturns.htm. >> C:\License.txt
echo As described below, using the software also operates as your consent to the transmission of certain computer information during activation, validation and for Internet-based services. >> C:\License.txt
echo If you comply with these license terms, you have the rights below for each license you acquire. >> C:\License.txt
echo 1.	OVERVIEW. >> C:\License.txt
echo a.	Software. The software includes desktop operating system software. This software does not include Windows Live services. Windows Live is a service available from Microsoft under a separate agreement. >> C:\License.txt
echo b.	License Model. The software is licensed on a per copy per computer basis. A computer is a physical hardware system with an internal storage device capable of running the software. A hardware partition or blade is considered to be a separate computer. >> C:\License.txt
echo 2.	INSTALLATION AND USE RIGHTS. >> C:\License.txt
echo a.	One Copy per Computer. You may install one copy of the software on one computer. That computer is the “licensed computer.” >> C:\License.txt
echo b.	Licensed Computer. You may use the software on up to two processors on the licensed computer at one time. Unless otherwise provided in these license terms, you may not use the software on any other computer. >> C:\License.txt
echo c.	Number of Users. Unless otherwise provided in these license terms, only one user may use the software at a time. >> C:\License.txt
echo d.	Alternative Versions. The software may include more than one version, such as 32-bit and 64-bit. You may install and use only one version at one time. >> C:\License.txt
echo 3.	ADDITIONAL LICENSING REQUIREMENTS AND/OR USE RIGHTS. >> C:\License.txt
echo a.	Multiplexing. Hardware or software you use to >> C:\License.txt
echo ·	pool connections, or >> C:\License.txt
echo ·	reduce the number of devices or users that directly access or use the software >> C:\License.txt
echo (sometimes referred to as “multiplexing” or “pooling”), does not reduce the number of licenses you need. >> C:\License.txt
echo b.	Font Components. While the software is running, you may use its fonts to display and print content. You may only >> C:\License.txt
echo ·	embed fonts in content as permitted by the embedding restrictions in the fonts; and >> C:\License.txt
echo ·	temporarily download them to a printer or other output device to print content. >> C:\License.txt
echo c.	Icons, images and sounds. While the software is running, you may use but not share its icons, images, sounds, and media. The sample images, sounds and media provided with the software are for your non-commercial use only. >> C:\License.txt
echo d.	Use with Virtualization Technologies. Instead of using the software directly on the licensed computer, you may install and use the software within only one virtual (or otherwise emulated) hardware system on the licensed computer. When used in a virtualized environment, content protected by digital rights management technology, BitLocker or any full volume disk drive encryption technology may not be as secure as protected content not in a virtualized environment. You should comply with all domestic and international laws that apply to such protected content. >> C:\License.txt
echo e.	Storage. You may store one copy of the software on a storage device, such as a network server. You may use that copy to install the software on any other computer to which a license has been assigned. >> C:\License.txt
echo f.	Device Connections. You may allow up to 20 other devices to access software installed on the licensed computer to use only File Services, Print Services, Internet Information Services and Internet Connection Sharing and Telephony Services. >> C:\License.txt
echo g.	Remote Access Technologies. You may access and use the software installed on the licensed computer remotely from another device using remote access technologies as follows. >> C:\License.txt
echo ·	Remote Desktop. The single primary user of the licensed computer may access a session from any other device using Remote Desktop or similar technologies. A “session” means the experience of interacting with the software, directly or indirectly, through any combination of input, output and display peripherals. Other users may access a session from any device using these technologies, if the remote device is separately licensed to run the software. >> C:\License.txt
echo ·	Other Access Technologies. You may use Remote Assistance or similar technologies to share an active session. >> C:\License.txt
echo h.	Media Center Extender. You may have five Media Center Extender Sessions (or other software or devices which provide similar functionality for a similar purpose) running at the same time to display the software user interface or content on other displays or devices. >> C:\License.txt
echo i.	Electronic Programming Guide. If the software includes access to an electronic programming guide service that displays customized television listings, a separate service agreement applies to the service. If you do not agree to the terms of the service agreement, you may continue to use the software, but you will not be able to use the electronic programming guide service. The service may contain advertising content and related data, which are received and stored by the software. The service is not available in all areas. Please consult the software information for instructions on accessing the service agreement. >> C:\License.txt
echo j.	Related Media Information. If you request related media information as part of your playback experience, the data provided to you may not be in your local language. Some countries or regions have laws and regulations which may restrict or limit your ability to access certain types of content. >> C:\License.txt
echo k.	Worldwide Use of the Media Center. Media Center is not designed for use in every country. For example, although the Media Center information may refer to certain features such as an electronic programming guide or provide information on how to configure a TV tuner, these features may not work in your area. Please refer to the Media Center information for a list of features that may not work in your area. >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo Eclipse Public License - v 1.0 >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE PUBLIC LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM CONSTITUTES RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT. >> C:\License.txt
echo 1. DEFINITIONS >> C:\License.txt
echo "Contribution" means: >> C:\License.txt
echo a) in the case of the initial Contributor, the initial code and documentation distributed under this Agreement, and >> C:\License.txt
echo b) in the case of each subsequent Contributor: >> C:\License.txt
echo i) changes to the Program, and >> C:\License.txt
echo ii) additions to the Program; >> C:\License.txt
echo where such changes and/or additions to the Program originate from and are distributed by that particular Contributor. A Contribution 'originates' from a Contributor if it was added to the Program by such Contributor itself or anyone acting on such Contributor's behalf. Contributions do not include additions to the Program which: (i) are separate modules of software distributed in conjunction with the Program under their own license agreement, and (ii) are not derivative works of the Program. >> C:\License.txt
echo "Contributor" means any person or entity that distributes the Program. >> C:\License.txt
echo "Licensed Patents " mean patent claims licensable by a Contributor which are necessarily infringed by the use or sale of its Contribution alone or when combined with the Program. >> C:\License.txt
echo "Program" means the Contributions distributed in accordance with this Agreement. >> C:\License.txt
echo "Recipient" means anyone who receives the Program under this Agreement, including all Contributors. >> C:\License.txt
echo 2. GRANT OF RIGHTS >> C:\License.txt
echo a) Subject to the terms of this Agreement, each Contributor hereby grants Recipient a non-exclusive, worldwide, royalty-free copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, distribute and sublicense the Contribution of such Contributor, if any, and such derivative works, in source code and object code form. >> C:\License.txt
echo b) Subject to the terms of this Agreement, each Contributor hereby grants Recipient a non-exclusive, worldwide, royalty-free patent license under Licensed Patents to make, use, sell, offer to sell, import and otherwise transfer the Contribution of such Contributor, if any, in source code and object code form. This patent license shall apply to the combination of the Contribution and the Program if, at the time the Contribution is added by the Contributor, such addition of the Contribution causes such combination to be covered by the Licensed Patents. The patent license shall not apply to any other combinations which include the Contribution. No hardware per se is licensed hereunder. >> C:\License.txt
echo c) Recipient understands that although each Contributor grants the licenses to its Contributions set forth herein, no assurances are provided by any Contributor that the Program does not infringe the patent or other intellectual property rights of any other entity. Each Contributor disclaims any liability to Recipient for claims brought by any other entity based on infringement of intellectual property rights or otherwise. As a condition to exercising the rights and licenses granted hereunder, each Recipient hereby assumes sole responsibility to secure any other intellectual property rights needed, if any. For example, if a third party patent license is required to allow Recipient to distribute the Program, it is Recipient's responsibility to acquire that license before distributing the Program. >> C:\License.txt
echo d) Each Contributor represents that to its knowledge it has sufficient copyright rights in its Contribution, if any, to grant the copyright license set forth in this Agreement. >> C:\License.txt
echo 3. REQUIREMENTS >> C:\License.txt
echo A Contributor may choose to distribute the Program in object code form under its own license agreement, provided that: >> C:\License.txt
echo a) it complies with the terms and conditions of this Agreement; and >> C:\License.txt
echo b) its license agreement: >> C:\License.txt
echo i) effectively disclaims on behalf of all Contributors all warranties and conditions, express and implied, including warranties or conditions of title and non-infringement, and implied warranties or conditions of merchantability and fitness for a particular purpose; >> C:\License.txt
echo ii) effectively excludes on behalf of all Contributors all liability for damages, including direct, indirect, special, incidental and consequential damages, such as lost profits; >> C:\License.txt
echo iii) states that any provisions which differ from this Agreement are offered by that Contributor alone and not by any other party; and >> C:\License.txt
echo iv) states that source code for the Program is available from such Contributor, and informs licensees how to obtain it in a reasonable manner on or through a medium customarily used for software exchange. >> C:\License.txt
echo When the Program is made available in source code form: >> C:\License.txt
echo a) it must be made available under this Agreement; and >> C:\License.txt
echo b) a copy of this Agreement must be included with each copy of the Program. >> C:\License.txt
echo Contributors may not remove or alter any copyright notices contained within the Program. >> C:\License.txt
echo Each Contributor must identify itself as the originator of its Contribution, if any, in a manner that reasonably allows subsequent Recipients to identify the originator of the Contribution. >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo  Apache License >> C:\License.txt
echo ------------------------------------------------------------- >> C:\License.txt
echo Version 2.0, January 2004 >> C:\License.txt
echo                         http://www.apache.org/licenses/ >> C:\License.txt
echo    TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION >> C:\License.txt
echo    1. Definitions. >> C:\License.txt
echo       "License" shall mean the terms and conditions for use, reproduction, >> C:\License.txt
echo       and distribution as defined by Sections 1 through 9 of this document. >> C:\License.txt
echo       "Licensor" shall mean the copyright owner or entity authorized by >> C:\License.txt
echo       the copyright owner that is granting the License. >> C:\License.txt
echo       "Legal Entity" shall mean the union of the acting entity and all >> C:\License.txt
echo       other entities that control, are controlled by, or are under common >> C:\License.txt
echo       control with that entity. For the purposes of this definition, >> C:\License.txt
echo       "control" means (i) the power, direct or indirect, to cause the >> C:\License.txt
echo       direction or management of such entity, whether by contract or >> C:\License.txt
echo       otherwise, or (ii) ownership of fifty percent (50%) or more of the >> C:\License.txt
echo       outstanding shares, or (iii) beneficial ownership of such entity. >> C:\License.txt
echo       "You" (or "Your") shall mean an individual or Legal Entity >> C:\License.txt
echo       exercising permissions granted by this License. >> C:\License.txt
echo       "Source" form shall mean the preferred form for making modifications, >> C:\License.txt
echo       including but not limited to software source code, documentation >> C:\License.txt
echo       source, and configuration files. >> C:\License.txt
echo       "Object" form shall mean any form resulting from mechanical >> C:\License.txt
echo       transformation or translation of a Source form, including but >> C:\License.txt
echo       not limited to compiled object code, generated documentation, >> C:\License.txt
echo       and conversions to other media types. >> C:\License.txt

move C:\\License.txt C:\Users\vagrant\Desktop